/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_research_bretl_robovidd_MainActivity */

#ifndef _Included_com_research_bretl_robovidd_MainActivity
#define _Included_com_research_bretl_robovidd_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_research_bretl_robovidd_MainActivity_PORT
#define com_research_bretl_robovidd_MainActivity_PORT 3490L
#undef com_research_bretl_robovidd_MainActivity_MAX_UDP_DATAGRAM_LEN
#define com_research_bretl_robovidd_MainActivity_MAX_UDP_DATAGRAM_LEN 64000L
/*
 * Class:     com_research_bretl_robovidd_MainActivity
 * Method:    decode_mat
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_com_research_bretl_robovidd_MainActivity_decode_1mat
  (JNIEnv *, jobject, jbyteArray, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
