/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_research_bretl_robovidd_MainActivity_ServerThread */

#ifndef _Included_com_research_bretl_robovidd_MainActivity_ServerThread
#define _Included_com_research_bretl_robovidd_MainActivity_ServerThread
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
